
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class Address
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Address()
    {

        this.contacts = new HashSet<contact>();

    }


    public int ID_address { get; set; }

    public int ID_district { get; set; }

    public int ID_town { get; set; }

    public string street { get; set; }

    public string house { get; set; }

    public Nullable<int> flat { get; set; }



    public virtual district district { get; set; }

    public virtual town town { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<contact> contacts { get; set; }

}

}
