//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classification()
        {
            this.Innovations = new HashSet<Innovation>();
        }
    
        public int ID_classification { get; set; }
        public int ID_prevelency { get; set; }
        public int ID_placeProdCycle { get; set; }
        public int ID_continuity { get; set; }
        public int ID_expMarShare { get; set; }
        public int ID_degreeNovelPot { get; set; }
        public int ID_degreeNovelMark { get; set; }
        public int ID_imactToEconomy { get; set; }
        public int ID_impactProdProc { get; set; }
        public int ID_impactFactProd { get; set; }
        public int ID_appArea { get; set; }
        public int ID_causeOf { get; set; }
        public int ID_chaMeetNeedsOf { get; set; }
    
        public virtual appArea appArea { get; set; }
        public virtual causeOf causeOf { get; set; }
        public virtual chaMeetNeedsOf chaMeetNeedsOf { get; set; }
        public virtual continuity continuity { get; set; }
        public virtual degreeNovelMark degreeNovelMark { get; set; }
        public virtual degreeNovelPot degreeNovelPot { get; set; }
        public virtual expMarShare expMarShare { get; set; }
        public virtual imactToEconomy imactToEconomy { get; set; }
        public virtual impactFactProd impactFactProd { get; set; }
        public virtual impactProdProc impactProdProc { get; set; }
        public virtual placeProdCycle placeProdCycle { get; set; }
        public virtual Prevelency Prevelency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Innovation> Innovations { get; set; }
    }
}
