//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contact()
        {
            this.Companies = new HashSet<Company>();
            this.Innovations = new HashSet<Innovation>();
            this.Innovations1 = new HashSet<Innovation>();
            this.realizations = new HashSet<realization>();
        }
    
        public int ID_contact { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string secondName { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> ID_address { get; set; }
        public Nullable<int> ID_CompanyState { get; set; }
        public int ID_PersonStatus { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        public virtual CompanyState CompanyState { get; set; }
        public virtual PersonStatu PersonStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Innovation> Innovations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Innovation> Innovations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<realization> realizations { get; set; }
    }
}
