//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationAboutCompany
    {
        public string name { get; set; }
        public string branch { get; set; }
        public string fieldActivity { get; set; }
        public string ware { get; set; }
        public string ownersheep { get; set; }
        public string district { get; set; }
        public string town { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public Nullable<int> flat { get; set; }
        public string house { get; set; }
        public string street { get; set; }
        public string secondName { get; set; }
        public string surname { get; set; }
        public int ID_company { get; set; }
        public string uname { get; set; }
    }
}
