
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class InformationAboutRealization
{

    public string Name_of_Innovation_Product { get; set; }

    public string Name_of_Company { get; set; }

    public string implementationState { get; set; }

    public string Surname_Promouter { get; set; }

}

}
