//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationAboutCompany
    {
        public string name { get; set; }
        public string branch { get; set; }
        public string fieldActivity { get; set; }
        public string ware { get; set; }
        public string ownersheep { get; set; }
    }
}
