//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationAboutInnovation
    {
        public string Name { get; set; }
        public int ID_innovation { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public string Expr12 { get; set; }
    }
}
