//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovationRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationAboutAuthor
    {
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Количество_проектов { get; set; }
        public string Индивидуальный_статус { get; set; }
        public string Должность { get; set; }
        public string email { get; set; }
        public string Область { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public Nullable<int> Квартира { get; set; }
        public string Телефон { get; set; }
    }
}
