
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class Innovation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Innovation()
    {

        this.realizations = new HashSet<realization>();

    }


    public string Name { get; set; }

    public int ID_innovation { get; set; }

    public int ID_innovWorksheet { get; set; }

    public int ID_contactAuthor { get; set; }

    public int ID_contactOwner { get; set; }

    public Nullable<int> ID_sertificate { get; set; }

    public Nullable<int> ID_stateInnov { get; set; }

    public string effeciency { get; set; }

    public Nullable<System.DateTime> lastUpdate { get; set; }

    public int ID_classification { get; set; }

    public string description { get; set; }



    public virtual Classification Classification { get; set; }

    public virtual contact contact { get; set; }

    public virtual contact contact1 { get; set; }

    public virtual innovationWorksheet innovationWorksheet { get; set; }

    public virtual Sertification Sertification { get; set; }

    public virtual StatesInnovation StatesInnovation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<realization> realizations { get; set; }

}

}
