
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class innovationWorksheet
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public innovationWorksheet()
    {

        this.Innovations = new HashSet<Innovation>();

    }


    public int ID_innowWorksheet { get; set; }

    public Nullable<int> ID_fieldActivity { get; set; }

    public Nullable<int> ID_branch { get; set; }

    public string ware { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual FieldActivity FieldActivity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Innovation> Innovations { get; set; }

}

}
