
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class License
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public License()
    {

        this.Sertifications = new HashSet<Sertification>();

    }


    public int ID_license { get; set; }

    public int numberLic { get; set; }

    public System.DateTime dateIssue { get; set; }

    public string licDescription { get; set; }

    public Nullable<int> ID_licenseCompany { get; set; }

    public Nullable<int> ID_company { get; set; }



    public virtual Company Company { get; set; }

    public virtual LicenseCompany LicenseCompany { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sertification> Sertifications { get; set; }

}

}
