
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InnovationRepository
{

using System;
    using System.Collections.Generic;
    
public partial class realization
{

    public int ID_realization { get; set; }

    public int ID_innovation { get; set; }

    public int ID_company { get; set; }

    public int ID_promoter { get; set; }

    public string implementationState { get; set; }



    public virtual Company Company { get; set; }

    public virtual contact contact { get; set; }

    public virtual Innovation Innovation { get; set; }

}

}
